#ifndef FS_ORGANIZER_VIEW_PLATFORM_WINDOWS_TITLE_BAR_H
#define FS_ORGANIZER_VIEW_PLATFORM_WINDOWS_TITLE_BAR_H

class QWidget;

void ApplySystemTitleBarTheme(const QWidget& window);

#endif // FS_ORGANIZER_VIEW_PLATFORM_WINDOWS_TITLE_BAR_H
