#ifndef FS_ORGANIZER_APPLICATION_MODEL_MANUAL_DELIVERY_H
#define FS_ORGANIZER_APPLICATION_MODEL_MANUAL_DELIVERY_H

enum class ManualDelivery
{
    Download,
    NotShipped,
};

#endif // FS_ORGANIZER_APPLICATION_MODEL_MANUAL_DELIVERY_H
