#ifndef FS_ORGANIZER_APPLICATION_MODEL_UPDATE_DELIVERY_H
#define FS_ORGANIZER_APPLICATION_MODEL_UPDATE_DELIVERY_H

enum class UpdateDelivery
{
    SelfUpdate,
    NoticeOnly,
};

#endif // FS_ORGANIZER_APPLICATION_MODEL_UPDATE_DELIVERY_H
