#ifndef FS_ORGANIZER_DOMAIN_MODEL_SIMULATOR_VARIANT_H
#define FS_ORGANIZER_DOMAIN_MODEL_SIMULATOR_VARIANT_H

enum class SimulatorVariant : int
{
    MSFS2020 = 0,
    MSFS2024 = 1,
};

#endif // FS_ORGANIZER_DOMAIN_MODEL_SIMULATOR_VARIANT_H
