set(DOMAIN_SOURCES
        src/domain/importing/CopyConflicts.cpp
        src/domain/importing/ImportEngine.cpp
        src/domain/journal/JournalEntries.cpp
        src/domain/journal/OperationLog.cpp
        src/domain/legacy/LegacyPreset.cpp
        src/domain/legacy/LegacyProposal.cpp
        src/domain/linking/DisableLinks.cpp
        src/domain/linking/EntryClassifier.cpp
        src/domain/linking/LinkingEngine.cpp
        src/domain/linking/RepairPlan.cpp
        src/domain/preset/PresetPlan.cpp
        src/domain/profile/OrphanOverrides.cpp
        src/domain/profile/ProfileEdits.cpp
        src/domain/tree/AddonTree.cpp
        src/domain/tree/CategorySuggester.cpp
        src/domain/tree/DestinationDivergence.cpp
        src/domain/tree/EffectiveDestination.cpp
        src/domain/tree/LibraryLookup.cpp
        src/domain/tree/LibraryTrees.cpp
        src/domain/tree/ToggleDirection.cpp
)

set(APPLICATION_SOURCES
        src/application/ImportService.cpp
        src/application/LegacyConfigImporter.cpp
        src/application/LibraryOrganizer.cpp
        src/application/PresetService.cpp
        src/application/ProfileService.cpp
        src/application/Session.cpp
        src/application/SetupService.cpp
)

set(INFRASTRUCTURE_SOURCES
        src/infrastructure/catalog/FilesystemScanner.cpp
        src/infrastructure/catalog/JsonManifestParser.cpp
        src/infrastructure/id/UuidLibraryIdGenerator.cpp
        src/infrastructure/journal/JsonlOperationJournal.cpp
        src/infrastructure/legacy/IniLegacyConfigReader.cpp
        src/infrastructure/legacy/LegacyPresetReader.cpp
        src/infrastructure/legacy/WindowsLegacyConfigSource.cpp
        src/infrastructure/preset/FilePresetRepository.cpp
        src/infrastructure/settings/JsonSettingsRepository.cpp
        src/infrastructure/sim/ContentListLocations.cpp
        src/infrastructure/sim/ContentXmlPackages.cpp
        src/infrastructure/sim/WindowsSimulatorLocator.cpp
        src/infrastructure/sim/WindowsUserCfgLocations.cpp
        src/infrastructure/update/GithubReleaseParser.cpp
)

set(WINDOWS_INFRASTRUCTURE_SOURCES
        src/infrastructure/fileops/ExtendedPaths.cpp
        src/infrastructure/fileops/WindowsFileOperations.cpp
        src/infrastructure/fileops/WindowsFilesystemProbe.cpp
        src/infrastructure/link/WindowsLinkService.cpp
        src/infrastructure/platform/SingleInstance.cpp
        src/infrastructure/platform/WindowsKnownFolders.cpp
        src/infrastructure/sim/WindowsProcessProbe.cpp
        src/view/platform/WindowsTitleBar.cpp
)

set(NETWORK_INFRASTRUCTURE_SOURCES
        src/infrastructure/update/GithubUpdateService.cpp
)

set(VIEWMODEL_SOURCES
        src/viewmodel/AddonTreeFilterModel.cpp
        src/viewmodel/AddonTreeModel.cpp
        src/viewmodel/AddonTreeViewModel.cpp
        src/viewmodel/CategorySuggestionModel.cpp
        src/viewmodel/CommunityModel.cpp
        src/viewmodel/CommunityViewModel.cpp
        src/viewmodel/FailureText.cpp
        src/viewmodel/ImportViewModel.cpp
        src/viewmodel/JournalModel.cpp
        src/viewmodel/JournalViewModel.cpp
        src/viewmodel/LegacyImportViewModel.cpp
        src/viewmodel/OptionsViewModel.cpp
        src/viewmodel/SimulatorText.cpp
        src/viewmodel/PresetViewModel.cpp
        src/viewmodel/QtBackgroundRunner.cpp
        src/viewmodel/QuarantineModel.cpp
        src/viewmodel/QuarantineViewModel.cpp
        src/viewmodel/SessionNotifier.cpp
        src/viewmodel/SetupViewModel.cpp
        src/viewmodel/UpdateViewModel.cpp
)

set(VIEW_SOURCES
        src/view/library/AddonTreePage.cpp
        src/view/community/CommunityPage.cpp
        src/view/community/ConflictDialog.cpp
        src/view/community/ImportDialog.cpp
        src/view/JournalPage.cpp
        src/view/shell/LanguageSwitch.cpp
        src/view/legacy/LegacyImportDialog.cpp
        src/view/options/OptionsPage.cpp
        src/view/delegates/FittedText.cpp
        src/view/delegates/PlainTextDelegate.cpp
        src/view/PresetsPage.cpp
        src/view/quarantine/QuarantinePage.cpp
        src/view/community/RepairDialog.cpp
        src/view/quarantine/RestoreDialog.cpp
        src/view/delegates/RowDelegate.cpp
        src/view/setup/SetupWizard.cpp
        src/view/setup/StagingLeftoverDialog.cpp
        src/view/shell/StartupOffers.cpp
        src/view/library/SuggestionDialog.cpp
        src/view/TableColumns.cpp
        src/view/WheelGuard.cpp
        src/view/panels/ContextPanel.cpp
        src/view/panels/EmptyState.cpp
        src/view/panels/ModelRowDetail.cpp
        src/view/panels/PanelRail.cpp
        src/view/shell/TriageStrip.cpp
        src/view/theme/ModernistPaint.cpp
        src/view/theme/ModernistStyle.cpp
        src/view/theme/ModernistTheme.cpp
        src/view/theme/ModernistTones.cpp
        src/view/shell/PageNames.cpp
        src/view/theme/PageTab.cpp
)

set(WINDOWS_SHELL_SOURCES
        src/view/shell/MainWindow.cpp
)

set(APP_SOURCES
        src/main.cpp
        ${NETWORK_INFRASTRUCTURE_SOURCES}
        ${WINDOWS_SHELL_SOURCES}
)

list(APPEND APP_SOURCES
        assets/app.rc
        assets/app.manifest
        assets/resources.qrc
)
